# Generated by Django 5.0 on 2023-12-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('x_coordinate', models.SmallIntegerField()),
                ('y_coordinate', models.SmallIntegerField()),
            ],
        ),
    ]
