# Generated by Django 4.2.1 on 2023-12-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_manual', '0006_place_restaurant_waiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sound', models.CharField(max_length=32)),
            ],
        ),
    ]
