# Generated by Django 4.2.1 on 2023-12-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_manual', '0008_blog_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
